<!-- bootstrap基础框架样式 -->
<link href="<c:url value='/st/css/bootstrap.min.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/st/css/bootstropmodel.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/st/css/plugins/datapicker/datepicker3.css'/>" rel="stylesheet" type="text/css">
<!-- 字体图标样式 -->
<link href="<c:url value='/st/css/font-awesome.min.css'/>" rel="stylesheet" type="text/css">
<!-- css动画样式 -->
<link href="<c:url value='/st/css/animate.min.css'/>" rel="stylesheet" type="text/css">
<!-- 下拉框样式 -->
<link href="<c:url value='/st/css/plugins/chosen/chosen.css'/>" rel="stylesheet" type="text/css">
<!-- zTree样式 -->
<link href="<c:url value='/st/css/plugins/zTree/metroStyle.css'/>" rel="stylesheet" type="text/css">
<!-- Sweet Alert样式 -->
<link href="<c:url value='/st/css/plugins/sweetalert/sweetalert.css'/>" rel="stylesheet" type="text/css">
<!-- mloading样式 -->
<link href="<c:url value='/st/css/plugins/mloading/jquery.mloading.css'/>" rel="stylesheet" type="text/css">
<!-- 自定义样式 -->
<link href="<c:url value='/st/css/style.css'/>" rel="stylesheet" type="text/css">
<!-- 分栏布局样式-->
<link href="<c:url value='/st/css/common.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/st/css/slide.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/st/css/flat-ui.min.css'/>" rel="stylesheet" type="text/css">
<link href="<c:url value='/st/css/jquery.nouislider.css'/>" rel="stylesheet" type="text/css">

<!-- 登录样式 -->
<link href="<c:url value='/st/css/login.css'/>" rel="stylesheet" type="text/css">
<!-- 个人信息样式-->
<link href="<c:url value='/st/css/manager.css'/>" rel="stylesheet" type="text/css">
<!-- 采购药品和药品出库样式-->
<link href="<c:url value='/st/css/record.css'/>" rel="stylesheet" type="text/css">
<!-- 查询页面样式-->
<link href="<c:url value='/st/css/search.css'/>" rel="stylesheet" type="text/css">
